### PR TITLE
Adding X-Amzn-Trace-Id in APIGW headers.

### PR DESCRIPTION
**Pull request by remychantenay**
*Description of changes:*
Adding `X-Amzn-Trace-Id` in the API Gateway headers. Often required in the logging strategy.
Not very useful per say, but having it in the headers avoid some nasty code workaround.

### CODE REVIEW

**Comment by sanathkr** [comment]
Thanks for the PR! Does API Gateway add the tracing ID on every request? Did you get to verify that?

Also unit tests are failing. Can you fix them?

**Comment by remychantenay** [comment]
Hi Sanath,

Thanks for your reply, sorry about the unit tests 👍 It should be good now.

From what I've experienced so far yes, APIGW sends a tracing ID on [every request](https://docs.aws.amazon.com/xray/latest/devguide/xray-services-apigateway.html). 

We are using it in our logging data at Travelex. The integration type is done with the type `LAMBDA_PROXY` and we always receive this information in the headers indeed.

Regarding the PR itself, I've added a hardcoded tracing ID (Root=1-00000000-000000000000000000000000) and not a dynamic one. The reason is that I assume nobody will actually use this header for a different purpose than logging (correct me if I am wrong here).

Hope it makes sense.

Thanks,
Remy

**Comment by jfuss** [comment]
@remychantenay The code looks good! 

Can you run ‘make func-test’ and ‘make integ-test’ locally? We haven’t yet updated Travis to run these targets yet but we have event serialization tests to ensure we don’t regress the event sent to the locally lambda.

Could you also add a small integ tests similar to the ones we have for the x-forward headers? https://github.com/awslabs/aws-sam-cli/blob/develop/tests/integration/local/start_api/test_start_api.py#L409

Functional tests: https://github.com/awslabs/aws-sam-cli/blob/develop/tests/functional/local/apigw/test_service.py#L66

**Comment by jfuss** [comment]
Looks like for ‘make func-test’ you will need to add ‘SAM_CLI_DEV=1’ before the command to run the tests against the dev version of the cli. ‘make integ-test’ looks to be already adding this. I will make sure this is in the guides going forward. Thanks!

Also, WOOT!!! On this bring your first PR here 🎉🎉

**Comment by jfuss** [comment]
I miss spoke on the ‘func-test’ command. The func-tests don’t run any cli specific code paths. So you shouldn’t need to add ‘SAM_CLI_DEV=1’ to that command.

**Comment by jfuss** [comment]
@remychantenay Where you ever able to run the func and integ tests?

**Comment by remychantenay** [comment]
Hi @jfuss 

It's been a bit crazy at work these couple of days so unfortunately, I can't spend much time on this, I will get back at it as soon as I have a bit more time 👍 👍 

Definitely on my list.

**Comment by jfuss** [comment]
@remychantenay Is this still on your list?

**Comment by jfuss** [comment]
@remychantenay I am going to close this PR. I will create a issue tracking the addition and link to this PR. If you get more time and want to continue on this, please submit a new PR.

**Comment by jfuss** [comment]
@remychantenay Looks like this can be reopened, so you can do that instead of creating a new one (which would be better imo).

**Pull request closed without merging**
