### PR TITLE
Update the .NET Core project template

### PR DESCRIPTION
**Pull request by normj**
*Description of changes:*
Cleaning up the project template created from `sam init` to be more .NET idiomatic

*Checklist:*

- [ ] Write Design Document ([Do I need to write a design document?](https://github.com/awslabs/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.rst#design-document))
- [ ] Write unit tests
- [ ] Write/update functional tests
- [ ] Write/update integration tests
- [ ] `make pr` passes
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by kiiadi** [comment]
@normj there's a bunch of unused imports in the `Function.cs` can we clean then up as part of this? The required imports for `Function.cs` should be (I believe): 

```
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Net.Http;
using Newtonsoft.Json;

using Amazon.Lambda.Core;
using Amazon.Lambda.APIGatewayEvents;
```

The `FunctionTest.cs` test file also seems to have some that aren't required. The required imports should be :

```
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Net.Http;
using Newtonsoft.Json;
using Xunit;
using Amazon.Lambda.TestUtilities;
using Amazon.Lambda.APIGatewayEvents;
```

There's also some other hints about best practice violations, for example `var ExpectedResponse` in `FunctionTest.cs` should start with a lower-case per convention right?

**Comment by normj** [comment]
Good catch, I didn't look at the FunctionTest for style issues. I pushed a new commit cleaning up the provided test case and unused namespaces. I did leave `System.Linq` because it provides a lot of extension methods to collections that surprise people when they don't show because `System.Linq` is not included.

I tested this by building and deploying my local version of the project and running the test case for the project.

**Comment by TheSriram** [comment]
@normj can I take over this PR? Looks like we need to rebase this.

**Comment by normj** [comment]
@TheSriram Yes feel free to take over the PR. You can ping me if you want to review any of the C# code.

**Pull request merged**
