### PR TITLE
docs(usage): Fix minor typo

### PR DESCRIPTION
**Pull request by anishkny**
*Issue #, if available:*

*Description of changes:* Fix minor typo in `docs/usage.md`

*Checklist:*

- [ ] Write Design Document ([Do I need to write a design document?](https://github.com/awslabs/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.rst#design-document))
- [ ] Write unit tests
- [ ] Write/update functional tests
- [ ] Write/update integration tests
- [ ] `make pr` passes
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by TheSriram** [comment]
Thanks for this catch 💯

**Comment by TheSriram** [comment]
I have re-kicked this build to get travis to pass.

**Comment by anishkny** [comment]
Thanks for an excellent tool!  🙏

**Comment by jfuss** [comment]
We no longer have the docs folder, as they are hosted in their own repo. I made the same change there: https://github.com/awsdocs/aws-sam-developer-guide/pull/21

Closing in favor of the awsdocs pr.

**Pull request closed without merging**
