### PR TITLE
Go debugging Delve API support

### PR DESCRIPTION
**Pull request by jackmcguire1**
*Issue #886 

*Description of changes:*
Update Usage documentation on how to run GO [Delve](https://github.com/go-delve/delve) debugger using API version 2 mode.

*Checklist:*

- [x] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by TheSriram** [comment]
This looks good to me.

**Comment by jfuss** [comment]
This should be updated directly on our docs right, since that is the source of truth? 
https://github.com/awsdocs/aws-sam-developer-guide

Side Note: @TheSriram and @sanathkr We need to make updates to push docs updates over there and remove the `.md` files that are no longer needed.

**Comment by jackmcguire1** [comment]
> This should be updated directly on our docs right, since that is the source of truth?
> https://github.com/awsdocs/aws-sam-developer-guide

Can I leave this for you guys to do, or would you like me to create an additional PR?

**Comment by TheSriram** [comment]
@jackmcguire1 Can you create the same PR on https://github.com/awsdocs/aws-sam-developer-guide. That repo should be our authoritative version of the docs.

**Pull request closed without merging**
