### PR TITLE
Docker proxy config

### PR DESCRIPTION
**Pull request by cooper3330**
*Issue #, if available:*

#913 

*Description of changes:*

This updates the docker create command to configure the proxy settings inside the docker container using global docker configuration file.  This will allow users who sit behind a proxy and have configured their proxy settings in docker to pass through their proxy for things such as dependency installation (Pip, etc.).

*Checklist:*

- [ ] Write Design Document ([Do I need to write a design document?](https://github.com/awslabs/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.rst#design-document))
- [ ] Write unit tests
- [ ] Write/update functional tests
- [ ] Write/update integration tests
- [ ] `make pr` passes
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by TheSriram** [comment]
Thanks for the contribution! 💯 

On first pass this looks good. I have some follow up questions

* https://github.com/docker/docker-py/blob/e2c1c9caace22098f7030049f0ad2f6d3f4e0f0a/docker/api/container.py#L396 states that appropriate env vars will be injected if proxy information is found in config file, [Docker proxy](https://docs.docker.com/network/proxy/) states that this is supported in Docker 17.07 and higher, does that mean this is not supported in the world of docker toolbox users? (mac and windows)
  * EDIT: https://github.com/docker/toolbox/releases -> Looks like it might be.
* what is an effective way to test this?

**Comment by cooper3330** [comment]
Testing this is an interesting case.  Since this is only modifying the Docker Container Create SDK call, I think we just need to test that the _container.create_ SDK call is kicked off with the expected parameter.  It is equivalent to including the _'tty=False'_ in the container create call.

To test these today, we are verifying the _Container Create_ call was kicked off with the correct parameters passed.  The proposed PR maintains that standard of testing with the underlying Docker SDKs by asserting _docker.create_ passed in the _use_config_proxy=True_ parameter.

Any issues/disagreement with that train of thought?

**Comment by sanathkr** [comment]
@cooper3330 Your testing rationale makes sense.

I digged thru Docker-Py's recent commit of https://github.com/docker/docker-py/pull/2202 to understand the implementation. I am confident that this doesn't have any side effects until you set proxy config in global Docker configuration files.

But this feature is available in Docker SDK >= 3.7.0. We need to update the version in `requirements/base.txt`

**Comment by sanathkr** [comment]
Bumping docker version separately - https://github.com/awslabs/aws-sam-cli/pull/1214 so we know this is safe before merging this.

**Pull request merged**
