### PR TITLE
Revert "Support debugging Golang functions."

### PR DESCRIPTION
**Pull request by jfuss**
Reverts awslabs/aws-sam-cli#495

### CODE REVIEW

**Comment by sanathkr** [comment]
Reverting because it caused functional & integ tests to fail.

**Comment by sanathkr** [comment]
Why are you reverting the proxy path change too?

**Comment by jfuss** [comment]
> Why are you reverting the proxy path change too?

Because github did that when I hit revert on the last golang commit. Let me try to fix that. Last time I use the UI for this :)

**Comment by jfuss** [comment]
I couldn't push to this revert branch here so pushed the revert to a new PR from my remote. 

Closing in favor of #526

**Pull request closed without merging**
