### PR TITLE
update README.md - simple typo fix

### PR DESCRIPTION
**Pull request by nyx**
*Issue #, if available:*

*Description of changes:*

simple typo fixes in README for Go

*Checklist:*

- [ ] Write Design Document ([Do I need to write a design document?](https://github.com/awslabs/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.rst#design-document))
- [ ] Write unit tests
- [ ] Write/update functional tests
- [ ] Write/update integration tests
- [ ] `make pr` passes
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by nyx** [comment]
also under the Building readme section "executeable" -> "executable". Sorry I have typo hawk-eye 😄

**Comment by nyx** [comment]
also under Building readme section "compatibility". Spell checker got me on that one I spell it the former way regularly.

**Comment by jfuss** [comment]
@nyx Thanks for all the corrections. Feel free to push any changes you come across in this PR or multiple (I know editing on github with spelling mistakes is usually easier).

**Comment by jfuss** [comment]
@nyx Please make sure you make the changes to track develop. The master branch is only merged to after we release from develop.

**Pull request merged**
