### PR TITLE
Bug fix - generate-event s3 URL encoding added

### PR DESCRIPTION
**Pull request by saaaaaaaaaahil**
*Issue #, if available:* Bug was that generate-event s3 --key ___ output was not URL encoded

*Description of changes:*
Added change to URL encode the key generated by generate-event s3 --key ___

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sanathkr** [comment]
@saaaaaaaaaahil Hey, can you fix the tests? `make pr` is failing

**Comment by jfuss** [comment]
@saaaaaaaaaahil Please make sure you are submitting PRs to develop and not master. The master branch is for releases only.

**Comment by sanathkr** [comment]
@saaaaaaaaaahil This PR needs be rebased against latest `develop` branch.

**Comment by sanathkr** [comment]
Closing because this is inactive

**Pull request closed without merging**
