### PR TITLE
Feature/lambda empty return

### PR DESCRIPTION
**Pull request by francilioaraujo**
*Issue #, if available:* #1161

*Why is this change necessary?* The API response when lambda doesn't provide a response was unintuitive.

*How does it address the issue?* The API return value was changed when lambda returns nothing.

*What side effects does this change have?* The API return value was changed to some cases and a log message was added

*Checklist:*

- [ ] Write Design Document ([Do I need to write a design document?](https://github.com/awslabs/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.rst#design-document))
- [ ] Write unit tests
- [ ] Write/update functional tests
- [x] Write/update integration tests
- [x] `make pr` passes
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by francilioaraujo** [comment]
@jfuss, I can't reproduce this error locally. I set up an ubuntu VM using vagrant and ran only the TestBuildCommand_Go_Modules inside test_build_cmd.py. Installed Go version 1.14 and python 3.8.0 inside the VM, But all 5 tests passed.
The lambda go function isn't returning the "{'message': 'Hello World'}" string on AppVeyor. On my VM the test passes. Could you give some clarification?

**Comment by jfuss** [comment]
@francilioaraujo I re-kicked off the failed tests. We have been seeing this randomly fail in appveyor but have not been able to root cause the issue.

**Comment by francilioaraujo** [comment]
@jfuss, thank you for re-executing the test. Now AppVeyor status is 'Completed' but the AppVeyor app on Github still shows as pending. Do we wait for it to update?

**Comment by jfuss** [comment]
@francilioaraujo Ya I just noticed that as well. There looks to be some kind of Github outage: https://www.githubstatus.com/incidents/q07bfjh7jf1t. This could be related to that. I wouldn't worry about it. I am going do another review pass right now though.

**Comment by jfuss** [comment]
@francilioaraujo I am going to check back here in a couple hours to see if Github catches up on the status so we don't have to do any manually overriding (I really don't want to kick off the whole build again, as it takes some time to actually finish). 

There shouldn't be any need for further updates from you at this point. Thanks for the contribution!

**Comment by francilioaraujo** [comment]
Thanks for all the support @jfuss. I'll be watching for updates.

**Pull request merged**
