### PR TITLE
list ruby as supported runtime

### PR DESCRIPTION
**Pull request by timoschilling**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jfuss** [comment]
@timoschilling While you are here, can you also add `Python3.7 and Provided` runtimes to the list. There is no init for `Provided`, though.

**Comment by TheSriram** [comment]
This is a great catch! thanks for adding this, could you add the other supported runtimes such as the ones @jfuss mentioned.

**Comment by timoschilling** [comment]
@jfuss applied

**Comment by jfuss** [comment]
@timoschilling Thank you! Just waiting for the build. Will merge shortly after that finishes.

**Pull request merged**
