### PR TITLE
Merge to master

### PR DESCRIPTION
**Pull request by sriram-mv**
*Why is this change necessary?*

Necessary to make a release.

*How does it address the issue?*

Move changes from develop to master.

* What side effects does this change have?*

None

*Checklist:*

- [ ] Write Design Document ([Do I need to write a design document?](https://github.com/awslabs/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.rst#design-document))
- [ ] Write unit tests
- [ ] Write/update functional tests
- [ ] Write/update integration tests
- [ ] `make pr` passes
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sriram-mv** [comment]
Dependent on https://github.com/awslabs/aws-sam-cli/pull/1709

**Comment by sriram-mv** [comment]
Unable to re-produce the regression test failures locally for deploy. Investigating.

**Comment by sanathkr** [comment]
Looks like the publish tests are failing on ubuntu for some reason. They are all passing on Windows. Publish tests failed on some S3 permissions. Deploy test failed on CFN API throttling.

**Linux**
```
tests/integration/publish/test_command_integ.py::TestPublishExistingApp::test_create_application_version_with_semantic_version_option FAILED                                                                                                       [ 95%]
tests/integration/publish/test_command_integ.py::TestPublishExistingApp::test_update_application FAILED
tests/integration/deploy/test_deploy_command.py::TestDeploy::test_deploy_twice_with_no_fail_on_empty_changeset_0_aws_serverless_function_yaml FAILED        
```

**Windows**
```
tests/integration/publish/test_command_integ.py::TestPublishExistingApp::test_create_application_version PASSED [ 95%]
tests/integration/publish/test_command_integ.py::TestPublishExistingApp::test_create_application_version_with_semantic_version_option PASSED [ 95%]
tests/integration/publish/test_command_integ.py::TestPublishExistingApp::test_update_application PASSED [ 96%]
tests/integration/publish/test_command_integ.py::TestPublishNewApp::test_create_application PASSED [ 96%]
tests/integration/publish/test_command_integ.py::TestPublishNewApp::test_create_application_infer_region_from_env PASSED [ 96%]
tests/integration/publish/test_command_integ.py::TestPublishNewApp::test_publish_not_packaged_template PASSED [ 97%]
```

**Comment by sanathkr** [comment]
Merging ignoring the failed test

**Pull request merged**
