### PR TITLE
chore: Bump up serverlessrepo version

### PR DESCRIPTION
**Pull request by paoptu023**
*Issue #, if available:*
https://github.com/awslabs/aws-serverlessrepo-python/pull/28

*Description of changes:*
Support using 'LicenseBody' and 'ReadmeBody' in application metadata properties.

*Checklist:*

- [ ] Write Design Document ([Do I need to write a design document?](https://github.com/awslabs/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.rst#design-document))
- [ ] Write unit tests
- [ ] Write/update functional tests
- [ ] Write/update integration tests
- [ ] `make pr` passes
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by awood45** [comment]
The failing test appears to be unrelated - are there any tests we may need to add to support any of these new features?

**Comment by jlhood** [comment]
@awood45 What's the next step here? I don't have access to the AppVeyor details so I don't know what the failure is. Is it a transient thing? Should we close/reopen the PR to kick off another build and retry?

**Comment by awood45** [comment]
The build failure seems unrelated, not concerned about that. I'm wanting to verify that there isn't any other expected work or new code paths we should test before upgrading. If there is not, I think we can move towards merging.

**Comment by jlhood** [comment]
@awood45 Thanks. I think it'd be a good idea to add a new integ test for this feature [here](https://github.com/awslabs/aws-sam-cli/blob/develop/tests/integration/publish/test_command_integ.py).

**Comment by jfuss** [comment]
@jlhood Did you ever work on those integ tests? Would love to get this in and close this one out.

**Comment by jlhood** [comment]
@jfuss I'd intended to work on them as part of an oncall shift, but that didn't end up happening. 😞

**Comment by jfuss** [comment]
Closing in favor of #1989

**Pull request closed without merging**
