### PR TITLE
Improve current init samples around docs and fixes

### PR DESCRIPTION
**Pull request by heitorlessa**
*Issue #, if available:*

*Description of changes:*

This PR addresses 5 feedbacks received from customers during Workshops as well as issues noted below:

* NodeJS and Python templates don't have links to API Gateway Event Object to aid on development (#518)
* NodeJS 8 template doesn't follow async await return syntax (#519)
* Python 2.7 runtime is used when ``sam init --runtime python`` is chosen and this should be Python3.6 (#521 )
* Manage try/catch across all runtimes to return HTTP 500 except Go (#520)
* DotNet core sample uses Cake and that doesn't in Cloud 9 or traditional setups for those beginning with DotNet Core that doesn't use Cake for simpler build/process (now dealt via PR https://github.com/awslabs/aws-sam-cli/pull/570)

---

~~Pending items to finalize this PR~~

- [X] Fix Try/Catch errors
    + [X] Nodejs needs to return 500 and print error
    + [X] Python needs to return 500 and print error
    + [X] Java is returning 400 instead of 500
- [X] Fix NodeJS promises
- [X] Fix python version (default)
- [X] Enhance docstrings -- API GW input/output
    + [X] Python
    + [C] NodeJS
- [C] Update tests to reflect changes
    + [X] Python

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jfuss** [comment]
@heitorlessa Why are we rolling back Dotnet Core enhancements?

**Comment by heitorlessa** [comment]
@joaoasrosa - Hey Joao, not sure you remember your PR for Cake (https://github.com/awslabs/aws-sam-cli/pull/401)...

I'm trying to run this through now on a mac with a fresh install of DotNet and I keep running into issues... as I dig into I noticed that NuGet.exe isn't anywhere in the system and while searching it seems I have to install Mono to get it working -- Is this expected? I couldn't see that in the README apart from running `build.sh`.

```bash
# Define directories.
SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
TOOLS_DIR=$SCRIPT_DIR/tools
ADDINS_DIR=$TOOLS_DIR/Addins
MODULES_DIR=$TOOLS_DIR/Modules
NUGET_EXE=$TOOLS_DIR/nuget.exe
CAKE_EXE=$TOOLS_DIR/Cake/Cake.exe
```

TOOLS_DIR doesn't exist within the dotnet core sample so perhaps this was stripped out accidentally?

I'd like to improve this example and make sure OSX, Linux and anyone running in Cloud9 is able to run this sample successfully so any help is more than appreciated :)

**Comment by joaoasrosa** [comment]
@heitorlessa yes I remember the PR. :)

Cake needs Mono and .NET Core in Unix based systems (more info [here](https://cakebuild.net/docs/overview/requirements)). 

Given your comment, we could enhance the README with the link, making it explicit to the users about the expectations for the system.

What are your thoughts?

**Comment by heitorlessa** [comment]
Yes!! That isn’t in the readme today and I started to receive feedback on
those as they can’t get passed the packaging/build steps.

Although mono is straightforward there must be some instructions on getting
those in place, path and such so others can do as part of the requirements,
and therefore I believe we should do this in a separate PR to collaborate
on that.

Would you be able to help creating a new PR and I can commit to those too?
If so, I can edit this and narrow this PR to other enhancements only.

Thanks a lot ;-)

**Comment by joaoasrosa** [comment]
Hi Heitor,

Sure thing I will. Give me a few hours to sort out some things, and I will
push it!

Cheers

**Comment by joaoasrosa** [comment]
@heitorlessa the PR #570 is done!

**Comment by heitorlessa** [comment]
Awesome @joaoasrosa !! Thanks for that. Just updated this PR to reflect that and @jfuss this is ready for review now and possibly merge ;)

**Comment by heitorlessa** [comment]
@jfuss ready for review!

**Pull request merged**
