### PR TITLE
Change cookiecutter URL to point at correct github repo

### PR DESCRIPTION
**Pull request by stealthycoin**
Removed the `hello` in the github reference since that repo does not exist.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by stealthycoin** [comment]
In any case the one I was changing it from is a 404: https://github.com/aws-samples/cookiecutter-aws-sam-hello-python. Someone else had reported that the SAM CLI  when used to run the template didn't set up the testing requirements properly (pytest etc) so I was trying out the cookiecutter template directly to see if it generated them. If it was actually a different template that I wound up running, it would make sense why it had the test dependencies declared and the other one didn't.

**Comment by jfuss** [comment]
That github doesn't exist and we should fix this doc but we can't change that reference the one you have since it is completely different. 

My point is that I think we should just remove those lines you changed but wanted to understand why it is the way it is now before moving forward.

**Comment by heitorlessa** [comment]
@jfuss This is an unpaid tech debt. README comes from unpublished repo before sam init was created; we're creating dedicated repo for each runtime as initially intended and moving these outside this repo. 

What customers should be reading today is not this README but the README that is generated as part of the template as these are raw files.

**Comment by jfuss** [comment]
@heitorlessa That doesn't mean we should keep it either though. If it does not provide any value, we should just remove it. Thoughts?

**Comment by heitorlessa** [comment]
I agree on removing it as it only confuses those who look up at the source
thinking this would provide any value

**Comment by jfuss** [comment]
@heitorlessa Are you talking these types of things in with your rework of all the init examples? Do we still need this if that is the case?

**Comment by jfuss** [comment]
@stealthycoin Thanks for the PR. We addressed this in a different PR (#849) while redoing some of the init examples. Closing this as it is no longer needed.

**Pull request closed without merging**
